# Welcome to Solomon's Blog!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: FutureForge
description: Hi, I'm Solomon! I'm an Electronics and Communication engineer originally from Chennai, India. From a young age, I've always been passionate about Robotics, Embedded Systems, and AI/ML. I love building systems and finding innovative ways to solve problems using these technologies.

For over 13 years, I had the privilege of working at Cisco Systems in Services, Operations, and Engineering. During my time there, I had the opportunity to build and implement complex systems, further honing my skills in the field.

Now, I'm focusing on learning more about ML to build even more advanced robots and embedded systems. I'm excited about the possibilities that this technology brings and I can't wait to see where it takes me next. I'm driven by my love for cutting-edge technology and the potential it has to change the world.
github_username: ichireisan

# Email and twitter are optional:
email: 
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
